import { TopBar } from '@/components/top-bar'
import type { Metadata } from 'next'
import { Readex_Pro } from 'next/font/google'
import type { FC, PropsWithChildren } from 'react'
import './globals.css'

const readexPro = Readex_Pro({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <html lang="en">
    <body className={readexPro.className}>
      <TopBar />
      {children}
    </body>
  </html>
)

export default RootLayout
